---

extends: default

rules:
  line-length:
    max: 120
    level: warning
  comments:
    require-starting-space: true
    ignore-shebangs: true
    min-spaces-from-content: 1
  document-start: disable
