name: 'CI'

on: # Build any PRs and main branch changes
  workflow_dispatch: # Allows to run the workflow manually from the Actions tab
  pull_request:
    types:
      - opened
      - synchronize
  push:
    branches: [ master ]
  schedule:
    - cron: '0 0 1 * *' # Every month

concurrency:
  group: "${{ github.workflow }}-${{ github.head_ref || github.ref }}"
  cancel-in-progress: true

jobs:
  tests:
    name: Run functional test
    runs-on: ubuntu-latest
    permissions:
      actions: write
    steps:
      - name: Dummy step
        shell: bash
        run: |
          echo "Dummy step, just to trigger underlying workflow run event"
