name: 'Trigger test repo workflow'
on:
  workflow_run:
    workflows: ["CI"]
    types: [completed]

jobs:
  tests:
    name: Run functional test
    runs-on: ubuntu-latest
    steps:
      - name: Trigger test repository worfklow
        env:
          GITHUB_TOKEN: ${{ secrets.FUNCTIONAL_TESTS_TRIGGER }}
        run: |
          gh api \
            --method POST \
            -H "Accept: application/vnd.github+json" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            /repos/yoanm/gha-versioning-test-repo/actions/workflows/functional-tests.yml/dispatches \
            -f "ref=master" \
            -f "inputs[sha]=${{ github.event.workflow_run.head_sha }}"
