name: 'Coverage'
on:
  workflow_run:
    workflows: ["CI"]
    types: [completed]

jobs:
  tests:
    name: Run functional test
    runs-on: ubuntu-latest
    permissions:
      actions: write
    steps:
      - name: DEBUG
        shell: bash
        run: |
          echo 'event='"'"'${{ toJson(github.event) }}'"'"

      - name: Trigger test repository worfklow
        env:
          GITHUB_TOKEN: ${{ github.token }}
        run: |
          gh api \
            --method POST \
            -H "Accept: application/vnd.github+json" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            /repos/yoanm/gha-versioning-test-repo/actions/workflows/functional-tests.yml/dispatches \
            -f "ref=master"  -f "inputs[ref]=${{ github.head_ref || github.ref }}"
